apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: erhc6s2d5-python
  janus-idp.io/tekton: erhc6s2d5-python
  backstage.io/kubernetes-id: erhc6s2d5-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: erhc6s2d5-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
